version: "3"

services:
  app:
      build: .
      ports: 
        - "8100:8100"
        - "35729:35729"
        - "53703:53703"
        - "53704:53704"
      volumes:
        - ".:/app"
      command: ionic serve